name: Demo Build

on: push

jobs:

  demonstration_build:

    runs-on: windows-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: dotnet build
      run: dotnet build
    - name: dotnet test
      run: dotnet test
