name: Nuget And Release Publication
on: workflow_dispatch
  
jobs:

  nuget_and_release_publication:

    runs-on: windows-latest 
    
    permissions:
      packages: write
      contents: write
      
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: dotnet pack
      run: dotnet pack
      working-directory: PowerCollections
      
    - name: dotnet nuget push --c Release
      run: dotnet nuget push "PowerCollections\bin\Release\*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/defizzz/index.json --skip-duplicate
      
    - name: Get prefix
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.1.1
      with: 
        xml-file: 'PowerCollections/PowerCollections.csproj'
        xpath: '//VersionPrefix'
        
    - name: Create Release 
      uses: ncipollo/release-action@v1.12.0
      with: 
        artifacts: 'PowerCollections\bin\Debug\*${{ steps.getxml.outputs.info }}.nupkg'
        tag: 'v${{ steps.getxml.outputs.info }}'
